development:
  adapter: postgresql
  database: task_master_development
test: &test
  adapter: postgresql
  database: task_master_test
production:
  adapter: postgresql
  database: task_master_production
cucumber:
  <<: *test
